#!/usr/bin/env python3
"""
Zo Agent Swarm — Sub-Agent Runner
Individual sub-agent execution script. Called via Zo API for each subtask.

This script is designed to be invoked by the coordinator. It receives a
subtask definition and executes it using its own tools and capabilities.

Usage (standalone, for testing):
    python swarm_agent.py --agent-type researcher --instruction "Research X" --output /tmp/out.md
"""

import argparse
import json
import sys
from pathlib import Path

# ── Agent Profiles ───────────────────────────────────────────────────────────

SKILL_DIR = Path(__file__).resolve().parent.parent
PROFILES_PATH = SKILL_DIR / "assets" / "agent_profiles.json"


def load_profile(agent_type: str) -> dict:
    with open(PROFILES_PATH) as f:
        profiles = json.load(f)
    return profiles.get(agent_type, profiles["generalist"])


def main():
    parser = argparse.ArgumentParser(description="Agent Swarm — Sub-Agent Runner")
    parser.add_argument("--agent-type", default="generalist",
                        help="Agent type (researcher, coder, writer, analyst, tester, generalist)")
    parser.add_argument("--instruction", required=True,
                        help="The specific instruction for this agent")
    parser.add_argument("--context", default="",
                        help="Background context for the task")
    parser.add_argument("--task-id", type=int, default=0,
                        help="Task identifier")
    parser.add_argument("--output", default="",
                        help="Output file path (if not specified, prints to stdout)")

    args = parser.parse_args()

    profile = load_profile(args.agent_type)

    # Build the full prompt
    prompt = profile["system_prompt"] + "\n\n"
    prompt += "─── YOUR SPECIFIC TASK ───\n"
    prompt += f"Task ID: {args.task_id}\n"
    prompt += f"Agent Type: {args.agent_type}\n\n"
    prompt += "INSTRUCTIONS:\n"
    prompt += args.instruction + "\n"

    if args.context:
        prompt += f"\nBACKGROUND CONTEXT:\n{args.context}\n"

    prompt += "\n─── OUTPUT REQUIREMENTS ───\n"
    prompt += "Produce your complete output. Be thorough and specific.\n"
    prompt += "This is part of a coordinated swarm — your output will be merged with others.\n"

    # Output the prompt
    output = f"# Agent Swarm Subtask {args.task_id}\n"
    output += f"# Type: {args.agent_type}\n"
    output += f"# Instruction: {args.instruction[:200]}...\n"
    output += f"# Profile: {profile['role']}\n\n"
    output += "## Prompt\n\n"
    output += prompt
    output += "\n\n## Response\n\n"
    output += "[Agent response would be generated by Zo API with this prompt]\n"

    if args.output:
        Path(args.output).write_text(output)
        print(f"Output written to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
